server:
  port: 7777
spring:
  datasource:
    #clickhouse 配置
    username: root
    password: sdfykjyxgs
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://192.168.101.83:8123/clickhouse_db
    #mysql 配置
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.101.83:3306/lock?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接池大小
      initial-size: 5
      #配置最小连接数
      min-idle: 5
      #配置最大连接数
      max-active: 20
      #配置连接等待超时时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #测试连接
      validation-query: SELECT 1 FROM user_info
#logging:
#  level:
#    com.clickhouse: debug
# cpu配置 2.9GHz 4核心 4G ssd
# 数据库      插入     耗时
# mysql      10w 1.1-1.2s 20w 4-8s+
# clickhouse 10w 1.5-1.6s 20w 2.9-3.0s 30w 4.5-4.7s 50w 7.6-7.9s 100w 15s